Traceback (most recent call last):
  File "c:\_Repositories\PythonTest\Projects\PythonStudy1\raiseAndAssert.py", line 62, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
